const fs = require('fs');
let c = fs.readFileSync('src/components/ProductsView_professional.vue', 'utf8');
const F = '\uFFFD';
const repl = {
  ['Categor'+F+'a']: 'Categoría',
  ['categor'+F+'a']: 'categoría',
  ['Categor'+F+'as']: 'Categorías',
  ['categor'+F+'as']: 'categorías',
  ['Cat'+F+'logo']: 'Catálogo',
  ['cat'+F+'logo']: 'catálogo',
  ['M'+F+'s']: 'Más',
  ['m'+F+'s']: 'más',
  ['Atr'+F+'s']: 'Atrás',
  ['atr'+F+'s']: 'atrás',
  ['t'+F+'rminos']: 'términos',
  ['T'+F+'rminos']: 'Términos',
  ['Electr'+F+'nico']: 'Electrónico',
  ['electr'+F+'nico']: 'electrónico',
  ['Bot'+F+'n']: 'Botón',
  ['Gesti'+F+'n']: 'Gestión',
  ['gesti'+F+'n']: 'gestión',
  ['expansi'+F+'n']: 'expansión',
  ['dise'+F+'ado']: 'diseñado',
  ['precisi'+F+'n']: 'precisión',
  ['Patr'+F+'n']: 'Patrón',
  ['m'+F+'vil']: 'móvil',
  ['reci'+F+'n']: 'recién',
  ['C'+F+'digo']: 'Código',
  ['c'+F+'digo']: 'código',
  ['Aceptaci'+F+'n']: 'Aceptación',
  ['facturaci'+F+'n']: 'facturación',
  ['Informaci'+F+'n']: 'Información',
  ['informaci'+F+'n']: 'información',
  ['Soluci'+F+'n']: 'Solución',
  ['soluci'+F+'n']: 'solución',
  ['Operaci'+F+'n']: 'Operación',
  ['operaci'+F+'n']: 'operación',
  ['Integraci'+F+'n']: 'Integración',
  ['integraci'+F+'n']: 'integración',
  ['Versi'+F+'n']: 'Versión',
  ['versi'+F+'n']: 'versión',
  ['Sesi'+F+'n']: 'Sesión',
  ['sesi'+F+'n']: 'sesión',
  ['generaci'+F+'n']: 'generación',
  ['configuraci'+F+'n']: 'configuración',
  ['recuperaci'+F+'n']: 'recuperación',
  ['validaci'+F+'n']: 'validación',
  ['actualizaci'+F+'n']: 'actualización',
  ['creaci'+F+'n']: 'creación',
  ['eliminaci'+F+'n']: 'eliminación',
  ['selecci'+F+'n']: 'selección',
  ['notificaci'+F+'n']: 'notificación',
  ['autenticaci'+F+'n']: 'autenticación',
  ['autorizaci'+F+'n']: 'autorización',
  ['conexi'+F+'n']: 'conexión',
  ['Direcci'+F+'n']: 'Dirección',
  ['direcci'+F+'n']: 'dirección',
  ['condici'+F+'n']: 'condición',
  ['Opci'+F+'n']: 'Opción',
  ['opci'+F+'n']: 'opción',
  ['descripci'+F+'n']: 'descripción',
  ['Descripci'+F+'n']: 'Descripción',
  ['comunicaci'+F+'n']: 'comunicación',
  ['transacci'+F+'n']: 'transacción',
  ['publicaci'+F+'n']: 'publicación',
  ['colecci'+F+'n']: 'colección',
  ['Colecci'+F+'n']: 'Colección',
  ['administraci'+F+'n']: 'administración',
  ['verificaci'+F+'n']: 'verificación',
  ['separaci'+F+'n']: 'separación',
  ['ubicaci'+F+'n']: 'ubicación',
  ['visualizaci'+F+'n']: 'visualización',
  ['paginaci'+F+'n']: 'paginación',
  ['implementaci'+F+'n']: 'implementación',
  ['Acci'+F+'n']: 'Acción',
  ['acci'+F+'n']: 'acción',
  ['Contrase'+F+'a']: 'Contraseña',
  ['contrase'+F+'a']: 'contraseña',
  ['C'+F+'dula']: 'Cédula',
  ['est'+F+' ']: 'está ',
  ['est'+F+'n']: 'están',
  ['Est'+F+' ']: 'Está ',
  [F+'xito']: 'éxito',
  ['m'+F+'dulo']: 'módulo',
  ['M'+F+'dulo']: 'Módulo',
  ['tel'+F+'fono']: 'teléfono',
  ['a'+F+'n']: 'aún',
  ['da'+F+'o']: 'daño',
  ['se'+F+'al']: 'señal',
  ['Berduras']: 'Verduras', // Fix verdura spelling from user prompt
  ['ba'+F+'o']: 'baño',
  ['ni'+F+'o']: 'niño',
  ['tama'+F+'o']: 'tamaño',
  ['T'+F+'tulo']: 'Título',
  ['t'+F+'tulo']: 'título',
  ['b'+F+'squeda']: 'búsqueda',
  ['B'+F+'squeda']: 'Búsqueda',
  ['autom'+F+'tico']: 'automático',
  ['Autom'+F+'tico']: 'Automático',
  ['autom'+F+'tica']: 'automática',
  ['Autom'+F+'tica']: 'Automática',
  ['art'+F+'culos']: 'artículos',
  ['Art'+F+'culos']: 'Artículos',
  ['art'+F+'culo']: 'artículo',
  ['Art'+F+'culo']: 'Artículo',
  ['pol'+F+'tica']: 'política',
  ['Pol'+F+'tica']: 'Política',
  ['l'+F+'nea']: 'línea',
  ['L'+F+'nea']: 'Línea',
  ['d'+F+'a']: 'día',
  ['D'+F+'a']: 'Día'
};
let replaced = 0;
for (let [k,v] of Object.entries(repl)) {
  if(c.includes(k)) {
    c = c.split(k).join(v);
    replaced++;
  }
}
fs.writeFileSync('src/components/ProductsView_professional.vue', c, 'utf8');
console.log('Words fixed:', replaced);
console.log('FFFD remaining:', (c.match(/\uFFFD/g) || []).length);
