export { default as HeroEditorial }   from './HeroEditorial.vue'
export { default as HeroSplit }       from './HeroSplit.vue'
export { default as HeroStreetwear } from './HeroStreetwear.vue'
export { default as HeroFocus }      from './HeroFocus.vue'
export { default as HeroPortrait }   from './HeroPortrait.vue'
// Variantes adicionales (disponibles para extensiones futuras)
export { default as HeroCarousel }   from './HeroCarousel.vue'
export { default as HeroCentered }   from './HeroCentered.vue'
export { default as HeroMinimal }    from './HeroMinimal.vue'
export { default as HeroImageGrid }  from './HeroImageGrid.vue'
export { default as HeroOverlay }        from './HeroOverlay.vue'
export { default as HeroDarkCinematic }  from './HeroDarkCinematic.vue'
export { default as HeroVideoLoop }      from './HeroVideoLoop.vue'
export { default as HeroParallax }       from './HeroParallax.vue'
export { default as HeroGradientWave }   from './HeroGradientWave.vue'
export { default as HeroGeneralPromo }   from './HeroGeneralPromo.vue'

